import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createRequire } from 'node:module';
const dir = mkdtempSync(join(tmpdir(), 'sentra-connectors-'));
let passed = 0;
try {
  execFileSync(process.execPath, ['node_modules/typescript/bin/tsc', '--module','commonjs','--moduleResolution','node','--target','ES2022','--skipLibCheck','--outDir',dir,'lib/connectors/service.ts'], {stdio:'inherit'});
  const require = createRequire(import.meta.url);
  const c = require(join(dir,'connectors/composio.js'));
  const { connectionAction } = require(join(dir,'connectors/service.js'));
  const { assertSameOrigin, readBoundedJson } = require(join(dir,'security/request.js'));
  delete process.env.SENTRA_SERVER_SECRET; delete process.env.VERCEL;
  process.env.COMPOSIO_API_KEY='fixture-key-only';
  process.env.COMPOSIO_CALLBACK_VERIFICATION_ENABLED='true';
  process.env.COMPOSIO_READ_ONLY_SCOPES_VERIFIED='true';
  process.env.SENTRA_APP_ORIGIN='https://sentra-ai-7lij.vercel.app';
  process.env.COMPOSIO_GMAIL_AUTH_CONFIG_ID='ac_gmail';
  process.env.COMPOSIO_SLACK_AUTH_CONFIG_ID='ac_slack';
  process.env.COMPOSIO_OUTLOOK_AUTH_CONFIG_ID='ac_outlook';
  const raw = { id:'ca_fixture', user_id:'user-a', status:'ACTIVE', toolkit:{slug:'gmail'}, auth_config:{id:'ac_gmail'}, state:{val:{access_token:'never-return-this'}} };
  let calls = []; let owner = 'user-a'; let status = 'ACTIVE'; let upstream;
  global.fetch=async(url, opts={}) => {
    if (String(url).startsWith('https://raw.githubusercontent.com/')) return new Response('bad.example\n');
    assert.ok(String(url).startsWith('https://backend.composio.dev/api/v3.1/'));
    assert.equal(opts.headers['x-api-key'],'fixture-key-only');
    assert.equal(opts.redirect,'error');
    calls.push({url:String(url), ...opts, body:opts.body ? JSON.parse(opts.body):undefined});
    if (upstream) return upstream(url,opts);
    const body=opts.body ? JSON.parse(opts.body):{};
    let result;
    if(String(url).includes('/auth_configs/')) result={toolkit:{slug:'gmail'},status:'ENABLED',auth_scheme:'OAUTH2'};
    else if(String(url).endsWith('/link')) result={connected_account_id:'ca_fixture',redirect_url:'https://connect.composio.dev/link/fixture'};
    else if(String(url).endsWith('/complete_auth')) result={connected_account_id:'ca_fixture',toolkit_slug:'gmail'};
    else if(String(url).endsWith('/revoke')) result={success:true};
    else if(String(url).includes('/tools/execute/proxy')) {
      assert.equal(body.connected_account_id,'ca_fixture'); assert.equal(body.method,'GET'); assert.ok(!body.custom_connection_data);
      if(body.endpoint.startsWith('https://gmail.googleapis.com/') && body.endpoint.includes('messages?')) result={status:200,data:{messages:[{id:'abc123'}]}};
      else if(body.endpoint.includes('messages/abc123')) result={status:200,data:{id:'abc123',payload:{mimeType:'text/plain',headers:[{name:'Subject',value:'Urgent verification'},{name:'From',value:'Scammer <evil@example.com>'}],body:{data:Buffer.from('URGENT: send your password immediately. https://bank.example@evil.example').toString('base64url')}}}};
      else if(body.endpoint.includes('graph.microsoft.com')) result={status:200,data:{value:[{id:'out1',subject:'Hello',from:{emailAddress:{address:'friend@example.com'}},body:{contentType:'text',content:'Meet tomorrow.'}}]}};
      else if(body.endpoint.includes('slack.com')) result={status:200,data:{ok:true,messages:[{ts:'1.2',user:'U1',text:'URGENT: send your password immediately.'}]}};
      else throw Error('Unexpected provider destination');
    } else if(String(url).includes('connected_accounts?')) result={items:[raw,{...raw,user_id:'user-b'}, {...raw,experimental:{account_type:'SHARED'}}]};
    else result={...raw,user_id:owner,status};
    return new Response(JSON.stringify(result),{headers:{'content-type':'application/json'}});
  };
  async function check(name, fn) { await fn(); passed++; console.log('PASS '+name); }
  await check('connections fail closed before callback verification is configured', async()=>{process.env.COMPOSIO_CALLBACK_VERIFICATION_ENABLED='false';assert.equal(c.configured('gmail'),false);await assert.rejects(connectionAction({action:'link',provider:'gmail',consent:true},'user-a'),e=>e.status===503);process.env.COMPOSIO_CALLBACK_VERIFICATION_ENABLED='true';});
  await check('no anonymous access or attacker-selected tool execution',async()=>{await assert.rejects(connectionAction({action:'scan'},''),e=>e.status===401);await assert.rejects(connectionAction({action:'GMAIL_SEND_EMAIL'},'user-a'),e=>e.status===400);});
  await check('connection and scan require literal opt-in',async()=>{for(const body of [{action:'link',provider:'gmail',consent:'true'},{action:'scan',accountId:'ca_fixture'}]) await assert.rejects(connectionAction(body,'user-a'),e=>e.status===400);});
  await check('account listing filters ownership and never returns tokens',async()=>{const list=await c.listAccounts('user-a');assert.deepEqual(list,[{id:'ca_fixture',provider:'gmail',status:'ACTIVE'}]);assert.ok(!JSON.stringify(list).includes('access_token'));});
  await check('cross-user scan and disconnect stop before any provider execution',async()=>{owner='user-b';calls=[];for(const action of ['scan','disconnect'])await assert.rejects(connectionAction({action,accountId:'ca_fixture',consent:true},'user-a'),e=>e.status===404);assert.equal(calls.filter(x=>x.url.includes('/proxy')||x.url.includes('/revoke')).length,0);owner='user-a';});
  await check('path traversal account IDs rejected before network requests',async()=>{calls=[];await assert.rejects(c.getAccount('../other','user-a'),e=>e.status===400);assert.equal(calls.length,0);});
  await check('inactive and shared accounts cannot scan',async()=>{status='REVOKED';await assert.rejects(c.getAccount('ca_fixture','user-a'),e=>e.status===409);status='ACTIVE';assert.throws(()=>c.accountForUser({...raw,experimental:{account_type:'SHARED'}},'user-a'),e=>e.status===404);});
  await check('Gmail read-only scan detects credential and URL deception without returning body',async()=>{calls=[];const report=await connectionAction({action:'scan',accountId:'ca_fixture',consent:true,userId:'user-b',endpoint:'https://evil.test'},'user-a');assert.equal(report.scanned,1);assert.equal(report.findings[0].decision,'BLOCK');assert.ok(report.findings[0].evidence.some(e=>e.title==='URL user-info detected'));assert.ok(!('text' in report.findings[0]));assert.equal(calls.filter(x=>x.url.includes('/proxy')).length,2);assert.ok(calls.filter(x=>x.url.includes('/proxy')).every(x=>x.body.endpoint.startsWith('https://gmail.googleapis.com/')));});
  await check('Outlook and Slack normalize bounded messages',async()=>{assert.equal((await c.readMessages({id:'ca_fixture',provider:'outlook',status:'ACTIVE'}))[0].title,'Hello');assert.ok((await c.readMessages({id:'ca_fixture',provider:'slack',status:'ACTIVE'},'C0123456789'))[0].text.includes('password'));await assert.rejects(c.readMessages({id:'ca_fixture',provider:'slack',status:'ACTIVE'},'https://evil.test'),e=>e.status===400);});
  await check('HTML hidden destinations retained; attachment content excluded',()=>{const m=c.gmailMessage({id:'x',payload:{mimeType:'multipart/mixed',parts:[{mimeType:'text/html',body:{data:Buffer.from('<a href="https://bank.example@evil.example">Safe bank</a>').toString('base64url')}},{mimeType:'text/plain',filename:'attachment.txt',body:{data:Buffer.from('attachment-secret').toString('base64url')}}]}});assert.ok(m.text.includes('https://bank.example@evil.example'));assert.ok(!m.text.includes('attachment-secret'));});
  await check('missing and truncated message bodies disclose incomplete coverage',()=>{assert.equal(c.gmailMessage({id:'x',snippet:'preview only'}).truncated,true);assert.equal(c.gmailMessage({id:'x',payload:{mimeType:'text/plain',body:{data:Buffer.from('a'.repeat(60000)).toString('base64url')}}}).truncated,true);});
  await check('OAuth initiation binds owner and fixed callback',async()=>{calls=[];const linked=await c.linkAccount('user-a','gmail');assert.equal(c.verifyPending(linked.pending,'user-a').accountId,'ca_fixture');const b=calls.find(x=>x.url.endsWith('/link')).body;assert.equal(b.user_id,'user-a');assert.equal(b.callback_url,'https://sentra-ai-7lij.vercel.app/api/connections/callback');});
  await check('OAuth cookie forgery, wrong user and expired callbacks rejected',()=>{const payload={userId:'user-a',provider:'gmail',accountId:'ca_fixture',expires:Date.now()+500000,nonce:'fixture'};const cookie=c.signPending(payload);assert.throws(()=>c.verifyPending(cookie,'user-b'));assert.throws(()=>c.verifyPending(cookie.slice(0,-1)+'X','user-a'));assert.throws(()=>c.verifyPending(c.signPending({...payload,expires:Date.now()-1}),'user-a'));assert.throws(()=>c.verifyPending(undefined,'user-a'));});
  await check('callback exchanges opaque URI under authenticated user only',async()=>{calls=[];const cookie=c.signPending({userId:'user-a',provider:'gmail',accountId:'ca_fixture',expires:Date.now()+500000,nonce:'fixture'});await c.completeConnection(cookie,'user-a','opaque-session');assert.deepEqual(calls.find(x=>x.url.endsWith('/complete_auth')).body,{session_uri:'opaque-session',user_id:'user-a'});await assert.rejects(c.completeConnection(cookie,'user-b','opaque-session'));});
  await check('upstream auth link open redirect rejected',async()=>{upstream=(url)=>new Response(JSON.stringify(String(url).includes('/auth_configs/')?{toolkit:{slug:'gmail'},status:'ENABLED',auth_scheme:'OAUTH2'}:{connected_account_id:'ca_fixture',redirect_url:'https://connect.composio.dev.evil.test/link'}));await assert.rejects(c.linkAccount('user-a','gmail'),e=>e.status===502);upstream=undefined;});
  await check('disconnect revokes owned connection only',async()=>{calls=[];assert.equal((await connectionAction({action:'disconnect',accountId:'ca_fixture'},'user-a')).disconnected,true);assert.ok(calls.some(x=>x.url.endsWith('/ca_fixture/revoke')));});
  await check('missing and forged Origin blocked; legitimate browser accepted',()=>{assert.throws(()=>assertSameOrigin(new Request('https://sentra.test/api/connections'),true),e=>e.status===403);assert.throws(()=>assertSameOrigin(new Request('https://sentra.test/api/connections',{headers:{origin:'https://evil.test'}}),true),e=>e.status===403);assertSameOrigin(new Request('https://sentra.test/api/connections',{headers:{origin:'https://sentra.test'}}),true);});
  await check('connection request body bounded before JSON parse',async()=>{await assert.rejects(readBoundedJson(new Request('https://sentra.test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({x:'a'.repeat(5000)})}),4096),e=>e.status===413);});
  await check('upstream error details and oversized payloads never escape',async()=>{upstream=()=>new Response('secret-internal-token',{status:500});await assert.rejects(c.listAccounts('user-a'),e=>e.status===502&&!e.message.includes('secret'));upstream=()=>new Response('a'.repeat(2000001));await assert.rejects(c.listAccounts('user-a'),e=>e.status===502);upstream=undefined;});
  console.log(`${passed} connector security checks passed against compiled implementation; provider responses are fixtures, not live OAuth.`);
} finally { rmSync(dir,{recursive:true,force:true}); }
