export default function PrivacyPage() {
  return <main className="min-h-screen px-6 py-10 text-white"><div className="mx-auto max-w-3xl">
    <a href="/" className="text-sm text-lime-200">Back to Sentra</a>
    <h1 className="mt-10 text-4xl font-semibold">Your data and Sentra’s limits</h1>
    <p className="mt-4 text-white/75">Product data guide · Updated October 6, 2026</p>
    <section className="mt-8 space-y-7 text-sm leading-7 text-white/80">
      <div><h2 className="text-xl font-semibold text-white">Investigate without saving</h2><p className="mt-2">Messages and URLs are sent to Sentra’s server for analysis. They are not saved as cases by default. Do not paste passwords, access tokens, payment details or unnecessary personal information. The server does not open URLs you submit; reputation checks use configured threat sources. Hosting and authentication providers may process request metadata and operational logs.</p></div>
      <div><h2 className="text-xl font-semibold text-white">When you choose to save</h2><p className="mt-2">Signing in and selecting Save this case stores a short input preview, the decision, explanation and evidence in Supabase under your account. Evidence can include fragments of your submitted message or URLs. Saved cases remain until you delete them; there is no automatic expiry currently. You can review or delete them from <a href="/cases" className="text-lime-200 underline">your saved investigations</a>. Deletion removes cases and evidence from the active database; it does not guarantee immediate removal from provider backups or operational logs.</p></div>
      <div><h2 className="text-xl font-semibold text-white">Optional AI review</h2><p className="mt-2">AI Council requires separate consent before sharing a case through Puter with the selected AI model providers. Their processing and retention policies apply. Local analysis works without this feature. AI outputs can be wrong and cannot guarantee that a message is safe.</p></div>
      <div><h2 className="text-xl font-semibold text-white">Connected accounts</h2><p className="mt-2">Composio handles platform authorization and tokens. When configured, Sentra reads recent messages from the account you select, after consent. These checks do not save message bodies as cases or send them to the AI Council. Disconnect in <a href="/connections" className="text-lime-200 underline">Connections</a> and review the platform’s authorized-app settings to revoke its permissions. Provider availability is shown in the interface.</p></div>
      <div><h2 className="text-xl font-semibold text-white">Your account and session</h2><p className="mt-2">Supabase processes the email and credentials used for sign-in and stores session cookies. You can sign out of the current session from your saved investigations. Deleting saved cases does not delete your sign-in account or revoke connected platforms. Self-service deletion of the authentication account is not available yet.</p></div>
      <div><h2 className="text-xl font-semibold text-white">A verdict is evidence, not a guarantee</h2><p className="mt-2">Sentra is an alpha for message and URL checks. A SAFE result means the available checks did not find enough suspicious evidence; it does not prove a sender or link is trustworthy. Feed outages and missing content reduce coverage. Verify important requests using a contact method you already trust. Media identity verification and full application scanning are not completed features.</p></div>
    </section>
  </div></main>;
}
